dataset: Ford_A
slice: True
model_folder: 'checkpoints/LSTM/Ford_A/'
save_path: results/Ford_A/IFGSM/Disc_reg_10
disc_path: 'results/Ford_A/IFGSM/Discriminator_pickle'

model_id_attack: 0

# attack_model:
#   _target_: models.models.TS2VecClassifier
#   dropout: None

attack_model:
  _target_: models.models.LSTM_net
  hidden_dim: 50
  n_layers: 1
  output_dim: 1
  dropout: 0.0

disc_model:
  _target_: models.models.LSTM_net
  hidden_dim: 50
  n_layers: 1
  output_dim: 1
  dropout: 0.0

# dataset: Ford_A
# model_folder: 'checkpoints/LSTM/Ford_A/'
# save_path: results/Ford_A/DeepFool/Original
# model_id_attack: 0

# attack_model:
#   _target_: models.models.LSTM_net
#   hidden_dim: 50
#   n_layers: 1
#   output_dim: 1
#   dropout: 0.2

# disc_model:
#   _target_: models.models.LSTM_net
#   hidden_dim: 50
#   n_layers: 1
#   output_dim: 1
#   dropout: 0.2

cuda: 'cuda:2'

attack_type: fgsm_disc_attack
n_iterations: 50
all_eps: [0.001, 0.0056, 0.0316, 0.1778, 1.0 ]  #  #[0.001, 0.01, 0.05, 0.2, 1.] #[0.1, 1.0, 10]
train_mode: True
batch_size: 64

alphas: [10, 1, 0.1, 100]

disc_check_params:
  model_id : 0
  model_name: fgsm_attack_eps=0.03_nsteps=10

list_reg_model_params:
 - model_id: 0
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.1_nsteps=10'
 - model_id: 0
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.01_nsteps=10'
 - model_id: 1
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.1_nsteps=10'
 - model_id: 1
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.01_nsteps=10'
 - model_id: 2
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.1_nsteps=10'
 - model_id: 2
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.01_nsteps=10'
 - model_id: 3
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.1_nsteps=10'
 - model_id: 3
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.01_nsteps=10'
 - model_id: 2
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.1_nsteps=10'
 - model_id: 2
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.01_nsteps=10'
 - model_id: 4
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.1_nsteps=10'
 - model_id: 4
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.01_nsteps=10'




