dataset: Ford_A

model_folder: 'checkpoints/Ford_A/'
model_id_attack: 1

cuda: 'cuda:2'

attack_type: fgsm_disc_attack
n_iterations: 50
eps_params: [0.001, 1.0, 5]
train_mode: True
batch_size: 64

disc_path: 'results/Ford_A/IFGSM/Regular/Discriminator_pickle'

disc_check_params:
  model_id : 0
  model_name: fgsm_attack_eps=0.03_nsteps=10

list_reg_model_params:
 - model_id: 0
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.01_nsteps=10'
 - model_id: 0
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.1_nsteps=10'
 - model_id: 1
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.01_nsteps=10'
 - model_id: 1
   model_name: 'fgsm_reg_attack_eps=0.03_alpha=0.1_nsteps=10'  


alphas: [1, 10, 0.1, 100]

save_path: results/Ford_A/IFGSM/Disc_reg_model_id_1